### ISSUE TITLE
Need examples of config files

### ISSUE THREAD

**Issue by codepope** [crabdancing/phomemo-d30#8]
There appear to be no sample config files in the repo, leaving one having to reverse out the file format from the source.

#6 compounds the problem by not making it clear that config files are not being found. 

Some examples would be helpful.

**Comment by crabdancing** [comment]
Yooo. Sorry about that; the schema wasn't totally stabilized when I was working on it. While this program is technically maintained, I haven't had the time to really polish it properly, and I'm honestly surprised there's that much interest in using it. :P I shall have to give it a little more polish soon.

There are two config files. On Linux, they are stored under `$XDG_CONFIG_HOME/phomemo-library`. On most systems, that will be `~/.config/phomemo-library` -- so I'll be using that path in this mini-guide to make this more concrete.

Under this directory, it expects two config files. One is for the library itself:

`~/.config/phomemo-library/phomemo-config.toml`

This is of a format like so:

```toml
# default device. E.g., if not specifying the target device, it will default to the kitchen.
# Side note: this can be the device name, or the MAC address.
default_device = "kitchen"
[resolution]
# Mappings device names to their corresponding device MAC addresses
my_desk = "40:5B:A4:2F:05:46"
kitchen = "DB:1E:B4:E7:A3:75"

```

You can think of this as a provisional/prototype `/etc/hosts` file but for mapping Bluetooth MAC addresses to human-friendly names. I name these according to where I have the Phomemo D30 machines I have stationed around the house.

The next file is for the CLI component:

`~/.config/phomemo-library/phomemo-cli-config.toml`

This one configures some bits of behavior, like for instance, the preview:

```toml
# This can be "gio", "wezterm", "show_image", or some custom command
preview = "gio"
# This can be true or false
enable_preview = true
```

Glossing over stuff that doesn't affect functionality that much here.

Also other things, like the ability to force dry run via TOML. Honestly, I don't even remember why that's in there. Probably a debugging thing.

Let me know if you have trouble getting it working. Best of luck. :)
